// import type { Metadata } from "next";
// import localFont from 'next/font/local'
import { Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";
import { Providers } from '@/store/provider';
import { Toaster } from 'sonner';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

/*const mundial = localFont({
  src: [
    {
      path: '../../public/fonts/MundialThin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/fonts/MundialLight.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/MundialRegular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/MundialDemibold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/MundialBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/MundialBlack.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-mundial',
  display: 'swap',
})*/

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable}  font-plus-jakarta-sans`}
      // className={`${mundial.variable} font-mundial`}
      >
        <Providers>{children}</Providers>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
